{'error_type': 'ZeroDivisionError', 'error_message': 'float division by zero', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 700, in updateData\n    data = updatelines(data, id, coordinate)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 401, in updatelines\n    result = circle_line_intersection(x1, y1, 3, x2, y2, x3, y3)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 375, in circle_line_intersection\n    t1 = (-b - math.sqrt(discriminant)) / (2 * a)\n         ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~\nZeroDivisionError: float division by zero\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
{'error_type': 'NameError', 'error_message': "name 'raja' is not defined", 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 659, in shrink_or_expand_points\n    args = select_and_rotate_coords(args,args["coordinates"],args["subdivision_list"],raja)\n                                                                                      ^^^^\nNameError: name \'raja\' is not defined\n'}
{'error_type': 'IndexError', 'error_message': 'list index out of range', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 664, in shrink_or_expand_points\n    subdiv_points[key] = [[new_x, new_y], value[1], value[2]]\n                                                    ~~~~~^^^\nIndexError: list index out of range\n'}
{'error_type': 'KeyError', 'error_message': "''", 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 827, in updateFromKml\n    b_ = data["coordinates"][b][0]\n         ~~~~~~~~~~~~~~~~~~~^^^\nKeyError: \'\'\n'}
{'error_type': 'KeyError', 'error_message': "''", 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 827, in updateFromKml\n    b_ = data["coordinates"][b][0]\n         ~~~~~~~~~~~~~~~~~~~^^^\nKeyError: \'\'\n'}
{'error_type': 'KeyError', 'error_message': "''", 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 827, in updateFromKml\n    b_ = data["coordinates"][b][0]\n         ~~~~~~~~~~~~~~~~~~~^^^\nKeyError: \'\'\n'}
{'error_type': 'KeyError', 'error_message': "''", 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 827, in updateFromKml\n    b_ = data["coordinates"][b][0]\n         ~~~~~~~~~~~~~~~~~~~^^^\nKeyError: \'\'\n'}
{'error_type': 'KeyError', 'error_message': "''", 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 827, in updateFromKml\n    for i in content.get("Line1", []):\n             ^^^^^^^^^^^^^^^^^^^^^^\nKeyError: \'\'\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
{'error_type': 'IndexError', 'error_message': 'list index out of range', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 687, in rotate\n    args = select_and_rotate_coords(args,args["coordinates"],args["subdivision_list"],raja)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 544, in select_and_rotate_coords\n    ret = get_relative_points(data,rajaresponse)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 448, in get_relative_points\n    pdf_an = compute_angle((box))\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/func.py", line 65, in compute_angle\n    return cord_angle(point_tp,point_elb,point_bs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/func.py", line 17, in cord_angle\n    print(p1[0] - p2[0], p1[1] - p2[1])\n          ~~^^^\nIndexError: list index out of range\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
{'error_type': 'IndexError', 'error_message': 'list index out of range', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 687, in rotate\n    args = select_and_rotate_coords(args,args["coordinates"],args["subdivision_list"],raja)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 544, in select_and_rotate_coords\n    ret = get_relative_points(data,rajaresponse)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 448, in get_relative_points\n    pdf_an = compute_angle((box))\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/func.py", line 65, in compute_angle\n    return cord_angle(point_tp,point_elb,point_bs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/func.py", line 17, in cord_angle\n    print(p1[0] - p2[0], p1[1] - p2[1])\n          ~~^^^\nIndexError: list index out of range\n'}
{'error_type': 'IndexError', 'error_message': 'list index out of range', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 687, in rotate\n    args = select_and_rotate_coords(args,args["coordinates"],args["subdivision_list"],raja)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 544, in select_and_rotate_coords\n    ret = get_relative_points(data,rajaresponse)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 448, in get_relative_points\n    pdf_an = compute_angle((box))\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/func.py", line 65, in compute_angle\n    return cord_angle(point_tp,point_elb,point_bs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/func.py", line 17, in cord_angle\n    print(p1[0] - p2[0], p1[1] - p2[1])\n          ~~^^^\nIndexError: list index out of range\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
{'error_type': 'StopIteration', 'error_message': '', 'traceback': 'Traceback (most recent call last):\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/pymodule.py", line 44, in process\n    return func(*args, **kwargs)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 237, in ExtractPdf\n    outer_polygon = lines_to_ring(outer_polygon)\n  File "/home/ubuntu/mypropertyqr-landsurvey/pydep/main.py", line 160, in lines_to_ring\n    start = next(iter(connections))\nStopIteration\n'}
